#include "dvr8833.h"
#include "dvr8833_defs.h"
#include "gpio.h"


void driver_port_reset(void)
{
	HAL_GPIO_WritePin(ENGINE_STANDBY_PORT, ENGINE_STANDBY_PORT_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(ENGINE_RIGHT_MOVE_FORWARD_PORT, ENGINE_RIGHT_MOVE_FORWARD_PORT_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(ENGINE_RIGHT_MOVE_BACK_PORT, ENGINE_RIGHT_MOVE_BACK_PORT_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(ENGINE_LEFT_MOVE_FORWARD_PORT, ENGINE_LEFT_MOVE_FORWARD_PORT_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(ENGINE_LEFT_MOVE_BACK_PORT, ENGINE_LEFT_MOVE_BACK_PORT_PIN, GPIO_PIN_RESET);
}

void driver_motor(E_MOTOR_COMMAND motorAction, E_MOTOR_STATUS *error_driver)
{
	E_STATUS status_driver = E_OK;
	switch (motorAction)
	{
	    case E_FORWARD:
			HAL_GPIO_WritePin(ENGINE_STANDBY_PORT, ENGINE_STANDBY_PORT_PIN, GPIO_PIN_SET);

			HAL_GPIO_WritePin(ENGINE_RIGHT_MOVE_FORWARD_PORT, ENGINE_RIGHT_MOVE_FORWARD_PORT_PIN, GPIO_PIN_SET);
			HAL_GPIO_WritePin(ENGINE_RIGHT_MOVE_BACK_PORT, ENGINE_RIGHT_MOVE_BACK_PORT_PIN, GPIO_PIN_RESET);

			HAL_GPIO_WritePin(ENGINE_LEFT_MOVE_FORWARD_PORT, ENGINE_LEFT_MOVE_FORWARD_PORT_PIN, GPIO_PIN_SET);
			HAL_GPIO_WritePin(ENGINE_LEFT_MOVE_BACK_PORT, ENGINE_LEFT_MOVE_BACK_PORT_PIN, GPIO_PIN_RESET);
			break;
		case E_BACK:
			HAL_GPIO_WritePin(ENGINE_STANDBY_PORT, ENGINE_STANDBY_PORT_PIN, GPIO_PIN_SET);

			HAL_GPIO_WritePin(ENGINE_RIGHT_MOVE_FORWARD_PORT, ENGINE_RIGHT_MOVE_FORWARD_PORT_PIN, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(ENGINE_RIGHT_MOVE_BACK_PORT, ENGINE_RIGHT_MOVE_BACK_PORT_PIN, GPIO_PIN_SET);

			HAL_GPIO_WritePin(ENGINE_LEFT_MOVE_FORWARD_PORT, ENGINE_LEFT_MOVE_FORWARD_PORT_PIN, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(ENGINE_LEFT_MOVE_BACK_PORT, ENGINE_LEFT_MOVE_BACK_PORT_PIN, GPIO_PIN_SET);
			break;
		case E_RIGHT:
			HAL_GPIO_WritePin(ENGINE_STANDBY_PORT, ENGINE_STANDBY_PORT_PIN, GPIO_PIN_SET);

			HAL_GPIO_WritePin(ENGINE_LEFT_MOVE_FORWARD_PORT, ENGINE_LEFT_MOVE_FORWARD_PORT_PIN, GPIO_PIN_SET);
			HAL_GPIO_WritePin(ENGINE_LEFT_MOVE_BACK_PORT, ENGINE_LEFT_MOVE_BACK_PORT_PIN, GPIO_PIN_RESET);
			break;
		case E_LEFT:
			HAL_GPIO_WritePin(ENGINE_STANDBY_PORT, ENGINE_STANDBY_PORT_PIN, GPIO_PIN_SET);

			HAL_GPIO_WritePin(ENGINE_RIGHT_MOVE_FORWARD_PORT, ENGINE_RIGHT_MOVE_FORWARD_PORT_PIN, GPIO_PIN_SET);
			HAL_GPIO_WritePin(ENGINE_RIGHT_MOVE_BACK_PORT, ENGINE_RIGHT_MOVE_BACK_PORT_PIN, GPIO_PIN_RESET);
			break
		case E_STOP:
			HAL_GPIO_WritePin(ENGINE_STANDBY_PORT, ENGINE_STANDBY_PORT_PIN, GPIO_PIN_RESET);

			HAL_GPIO_WritePin(ENGINE_RIGHT_MOVE_FORWARD_PORT, ENGINE_RIGHT_MOVE_FORWARD_PORT_PIN, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(ENGINE_RIGHT_MOVE_BACK_PORT, ENGINE_RIGHT_MOVE_BACK_PORT_PIN, GPIO_PIN_RESET);

			HAL_GPIO_WritePin(ENGINE_LEFT_MOVE_FORWARD_PORT, ENGINE_LEFT_MOVE_FORWARD_PORT_PIN, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(ENGINE_LEFT_MOVE_BACK_PORT, ENGINE_LEFT_MOVE_BACK_PORT_PIN, GPIO_PIN_RESET);
			break
		default:
			status_driver = E_ERROR;
			break;
	}
	*error_driver = status_driver;
}

